- name: Ensure the target working directory is empty
  block:
    - name: Remove current working directory
      file:
        path: "{{ working_dir }}"
        state: absent
    - name: Create working directory
      file:
        path: "{{ working_dir }}"
        state: directory
- name: Clone mu repository
  git:
    repo: "{{ repository }}"
    dest: "{{ working_dir }}"
    version: 'HEAD'
  notify:
    - Set working directory ownership
    - Build mu
    - Install mu
